services:
  api:
    build: ./CDA-api
    environment:
      - WDS_SOCKET_PORT=5001
      - WATCHPACK_POLLING=true
    env_file:
      - ./CDA-api/.env
    ports:
      - 5001:5001
    volumes:
      - ./CDA-api/src:/app/src
      - ./CDA-api/utils:/app/utils
  app:
    build: ./CDA-app
    environment:
      - WDS_SOCKET_PORT=8081
      - WATCHPACK_POLLING=true
    ports:
      - 8081:8081
    env_file:
      - ./CDA-app/.env
    command: yarn run staging-preview
    depends_on: [api]
  nginx:
    image: nginx:1.21.3
    depends_on:
      - api
      - app
    restart: always
    ports:
      - ${GATEWAY_PORT:-8001}:81
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./logs:/var/log/nginx
