services:
  api:
    build:
      context: ./CDA-api
      dockerfile: Dockerfile
    environment:
      - WDS_SOCKET_PORT=5000
      - WATCHPACK_POLLING=true
    ports:
      - 5000:5000
    command: npm run kiss
    volumes:
      - ./CDA-api:/app
  app:
    build:
      context: ./CDA-app
      dockerfile: Dockerfile
    environment:
      - WDS_SOCKET_PORT=8080
      - WATCHPACK_POLLING=true
    ports:
      - 8080:8080
    env_file:
      - ./CDA-api/.env
    command: yarn start
    volumes:
      - ./CDA-app:/app
    depends_on: [api]
  mongodb:
    image: mongo
    volumes:
      - ./CDA-api/mongo:/data/mongo
