services:
  staging-api:
    build: ./CDA-api
    environment:
      - WDS_SOCKET_PORT=5000
      - WATCHPACK_POLLING=true
    env_file:
      - ./CDA-api/.env
    ports:
      - 5000:5000
    volumes:
      - ./CDA-api/src:/app/src
      - ./CDA-api/utils:/app/utils
  staging-app:
    build: ./CDA-app
    environment:
      - WDS_SOCKET_PORT=8080
      - WATCHPACK_POLLING=true
    ports:
      - 8080:8080
    command: yarn run start-prod
    volumes:
      - ./CDA-app/src:/app/src
    depends_on: [api]
  staging-mongodb:
    image: mongo
    volumes:
      - ./CDA-api/mongo:/data/mongo
  staging-nginx:
    image: nginx:1.21.3
    depends_on:
      - api
      - app
    restart: always
    ports:
      - ${GATEWAY_PORT:-8001}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./logs:/var/log/nginx
