services:
  api:
    build: ./CDA-api
    environment:
      - WDS_SOCKET_PORT=5000
      - WATCHPACK_POLLING=true
    env_file:
      - ./CDA-api/.env
    ports:
      - 5000:5000
    volumes:
      - ./CDA-api/src:/app/src
      - ./CDA-api/utils:/app/utils
  app:
    build: ./CDA-app
    environment:
      - WDS_SOCKET_PORT=8080
      - WATCHPACK_POLLING=true
    ports:
      - 8080:8080
    command: yarn start
    volumes:
      - ./CDA-app/src:/app/src
    depends_on: [api]
  mongodb:
    image: mongo
    volumes:
      - ./CDA-api/mongo:/data/mongo
