services:
  api:
    build: ./CDA-api
    environment:
      - WDS_SOCKET_PORT=5000
      - WATCHPACK_POLLING=true
    env_file:
      - ./CDA-api/.env
    ports:
      - 5000:5000
    volumes:
      - ./CDA-api/src:/app/src
      - ./CDA-api/utils:/app/utils
  app:
    build: ./CDA-app
    environment:
      - WDS_SOCKET_PORT=8080
      - WATCHPACK_POLLING=true
    ports:
      - 8080:8080
    command: yarn run preview
    depends_on: [api]
  mongodb:
    image: mongo
    volumes:
      - ./CDA-api/mongo:/data/mongo
  nginx:
    image: nginx:1.21.3
    depends_on:
      - api
      - app
    restart: always
    ports:
      - ${GATEWAY_PORT:-8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./logs:/var/log/nginx
