name: Node.js CI

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ * ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up --build -d
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: build api
      - run: docker compose exec cda-project-api-1 npm ci
      - run: docker compose exec cda-project-api-1 npm run build --if-present
      - name: run tests
      - run: docker compose exec cda-project-api-1 npm test